---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildpacks-ws-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: buildpacks-pipelinerun-
  labels:
    app.kubernetes.io/description: PipelineRunTest
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: buildpacks
  params:
    - name: BUILDER_IMAGE
      value: paketobuildpacks/builder:base
    - name: TRUST_BUILDER
      value: "true"
    - name: APP_IMAGE
      value: ""
    - name: CONTAINER_IMAGE_REPO
      value: kbachman/kubernetes
    - name: SOURCE_URL
      value: https://github.com/kwbach/springboot_health
    - name: SOURCE_SUBPATH
      value: ""
  workspaces:
    - name: source-ws
      subPath: source
      persistentVolumeClaim:
        claimName: buildpacks-ws-pvc
    - name: cache-ws
      subPath: cache
      persistentVolumeClaim:
        claimName: buildpacks-ws-pvc